-- 1. Create a table for user profiles (synced from Neon Auth / Better Auth)
create table if not exists public.profiles (
  id text primary key,
  email text,
  full_name text,
  role text, -- 'Patient', 'Seller', 'Doctor'
  mobile text,
  extra_details jsonb, -- address, GST number, specialization, reg council etc.
  created_at timestamp with time zone default now()
);

-- Enable RLS on profiles
alter table public.profiles enable row level security;

-- Policies for profiles
drop policy if exists "Profiles are viewable by everyone" on public.profiles;
create policy "Profiles are viewable by everyone" on public.profiles
  for select using (true);

drop policy if exists "Anyone can insert profiles" on public.profiles;
create policy "Anyone can insert profiles" on public.profiles
  for insert with check (true);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile" on public.profiles
  for update using (true);


-- 2. Create medicines catalog table
create table if not exists public.medicines (
  id bigint generated by default as identity primary key,
  name text not null,
  generic_name text not null,
  price double precision not null,
  stock integer not null,
  category text not null,
  requires_prescription boolean not null default false,
  created_at timestamp with time zone default now()
);

-- Enable RLS on medicines
alter table public.medicines enable row level security;

-- Policies for medicines
drop policy if exists "Medicines are viewable by everyone" on public.medicines;
create policy "Medicines are viewable by everyone" on public.medicines
  for select using (true);

drop policy if exists "Anyone can insert medicines" on public.medicines;
create policy "Anyone can insert medicines" on public.medicines
  for insert with check (true);

drop policy if exists "Anyone can update medicines" on public.medicines;
create policy "Anyone can update medicines" on public.medicines
  for update using (true);

drop policy if exists "Anyone can delete medicines" on public.medicines;
create policy "Anyone can delete medicines" on public.medicines
  for delete using (true);


-- 3. Create orders table
create table if not exists public.orders (
  id text primary key,
  patient_id text,
  patient_name text not null,
  items jsonb not null, -- Array of OrderItem: name, quantity, price
  status text not null, -- Pending, Accepted, Packed, OutForDelivery, Delivered, Declined
  prescription_url text,
  created_at timestamp with time zone default now()
);

-- Enable RLS on orders
alter table public.orders enable row level security;

-- Policies for orders
drop policy if exists "Anyone can view orders" on public.orders;
create policy "Anyone can view orders" on public.orders
  for select using (true);

drop policy if exists "Anyone can insert orders" on public.orders;
create policy "Anyone can insert orders" on public.orders
  for insert with check (true);

drop policy if exists "Anyone can update orders" on public.orders;
create policy "Anyone can update orders" on public.orders
  for update using (true);


-- 4. Create payouts table
create table if not exists public.payouts (
  id text primary key,
  amount double precision not null,
  status text not null, -- Settled, Pending
  created_at timestamp with time zone default now()
);

-- Enable RLS on payouts
alter table public.payouts enable row level security;

-- Policies for payouts
drop policy if exists "Anyone can view payouts" on public.payouts;
create policy "Anyone can view payouts" on public.payouts
  for select using (true);

drop policy if exists "Anyone can insert payouts" on public.payouts;
create policy "Anyone can insert payouts" on public.payouts
  for insert with check (true);


-- 5. Create prescriptions table
create table if not exists public.prescriptions (
  id text primary key,
  patient_name text not null,
  doctor_name text not null,
  medicines jsonb not null, -- Array of OrderItem: name, quantity, price
  instructions text,
  created_at timestamp with time zone default now()
);

-- Enable RLS on prescriptions
alter table public.prescriptions enable row level security;

-- Policies for prescriptions
drop policy if exists "Anyone can view prescriptions" on public.prescriptions;
create policy "Anyone can view prescriptions" on public.prescriptions
  for select using (true);

drop policy if exists "Anyone can insert prescriptions" on public.prescriptions;
create policy "Anyone can insert prescriptions" on public.prescriptions
  for insert with check (true);


-- 6. Insert initial seed data for medicines
insert into public.medicines (name, generic_name, price, stock, category, requires_prescription)
values 
  ('Paracetamol 500mg', 'Acetaminophen', 45.0, 150, 'Analgesic', false),
  ('Amoxicillin 250mg', 'Amoxicillin', 120.0, 80, 'Antibiotic', true),
  ('Atorvastatin 10mg', 'Atorvastatin', 240.0, 4, 'Cardiovascular', true),
  ('Metformin 500mg', 'Metformin', 85.0, 120, 'Antidiabetic', true),
  ('Cetirizine 10mg', 'Cetirizine', 30.0, 200, 'Antihistamine', false),
  ('Ibuprofen 400mg', 'Ibuprofen', 55.0, 0, 'Analgesic', false),
  ('Daily Multivitamins', 'Multivitamins & Minerals', 499.0, 50, 'Wellness', false),
  ('Ashwagandha Forte', 'Ashwagandha Extract', 320.0, 35, 'Ayurveda', false)
on conflict do nothing;

-- 7. Insert initial seed data for payouts
insert into public.payouts (id, amount, status, created_at)
values 
  ('TXN-3912', 2450.0, 'Settled', now() - interval '3 days'),
  ('TXN-3881', 1890.0, 'Settled', now() - interval '5 days'),
  ('TXN-3710', 4120.0, 'Settled', now() - interval '8 days')
on conflict do nothing;


-- 8. Grant access to schema and tables for Neon Auth roles
grant usage on schema public to anonymous, authenticated;
grant all privileges on all tables in schema public to anonymous, authenticated;
grant all privileges on all sequences in schema public to anonymous, authenticated;
